Class {
	#name : #PSBlock2RodAndStealOn3Rod,
	#superclass : #'PSBlockingAndStealing_',
	#category : #FMR
}

{ #category : #awards }
PSBlock2RodAndStealOn3Rod >> awardName [
^'Best Ever 3-rod Block and Steal from 2-rod Rate'
]

{ #category : #generation }
PSBlock2RodAndStealOn3Rod >> sequence [
^'2c|.|3c'
]

{ #category : #generation }
PSBlock2RodAndStealOn3Rod >> statisticName [
^'3-rod block and steal from 2-rod'
]
