Class {
	#name : #PSBlock5RodAndStealOn5Rod,
	#superclass : #'PSBlockingAndStealing_',
	#category : #FMR
}

{ #category : #awards }
PSBlock5RodAndStealOn5Rod >> awardName [
^'Best Ever 5-rod Block and Steal from 5-rod Rate'
]

{ #category : #generation }
PSBlock5RodAndStealOn5Rod >> sequence [
^'5c|.|5c'
]

{ #category : #UI }
PSBlock5RodAndStealOn5Rod >> statisticName [
^'5-rod block and steal from 5-rod'
]
