Class {
	#name : #PSBlock3RodAndStealOn2Rod,
	#superclass : #'PSBlockingAndStealing_',
	#category : #FMR
}

{ #category : #generation }
PSBlock3RodAndStealOn2Rod >> sequence [
^'3c|.|2c'
]

{ #category : #UI }
PSBlock3RodAndStealOn2Rod >> statisticBalloonMacro [
^'In <g> <tt> blocked and retained the ball shot <s2> times on their <r2> following <r1> controlled possessions on <ot>''s <r1>.'
]

{ #category : #generation }
PSBlock3RodAndStealOn2Rod >> statisticName [
^'2-rod block and steal from 3-rod'
]
